### ISSUE TITLE
Which accelerate version do you use?

### ISSUE THREAD

**Issue by lunaryan** [AAAAAAsuka/Impress#4]
Hi, I am using accelerate 0.21.0 and encounter socket timeout error (see below) when finetune SD model, I am wondering which version do you use?

Traceback (most recent call last):
  File "/home/miniconda3/envs/py3.8/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 736, in run
    result = self._invoke_run(role)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 871, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 705, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 549, in _rendezvous
    workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 637, in _assign_worker_ranks
    role_infos = self._share_and_gather(store, group_rank, group_world_size, spec)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 674, in _share_and_gather
    role_infos_bytes = store_util.synchronize(
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 64, in synchronize
    agent_data = get_all(store, rank, key_prefix, world_size)
  File "/home/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 34, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout

Also, in test_all.sh, line #49 should be a comment, right? Thanks!

**Comment by AAAAAAsuka** [comment]
Hi,

The version of accelerate I'm using is 0.22.0. I haven't encountered this error when running the experiments, can you try to see if the code works correctly with version 0.22.0 of accelerate? 

Also in test_all.sh, line 49 should indeed be a comment, I've changed this file, thanks for the heads up!

**Comment by lunaryan** [comment]
Thanks so much for your reply! However, it does not solve the issue. Could you also check the pytorch version? My environment is:
Package                  Version
------------------------ ------------
accelerate               0.22.0
aiohttp                  3.8.6
aiosignal                1.3.1
appdirs                  1.4.4
async-timeout            4.0.3
attrs                    23.1.0
beautifulsoup4           4.12.2
blessed                  1.20.0
certifi                  2023.5.7
charset-normalizer       2.0.12
click                    8.1.7
cmake                    3.27.6
cycler                   0.11.0
datasets                 2.14.3
diffusers                0.23.1
dill                     0.3.7
docker-pycreds           0.4.0
easydict                 1.9
filelock                 3.12.4
fonttools                4.39.4
frozenlist               1.4.0
fsspec                   2023.9.2
gdown                    4.7.1
gitdb                    4.0.10
GitPython                3.1.37
gpustat                  1.1.1
huggingface-hub          0.16.4
idna                     3.4
imageio                  2.16.0
importlib-metadata       6.8.0
Jinja2                   3.1.2
joblib                   1.3.2
jsonlines                4.0.0
kiwisolver               1.4.4
lit                      17.0.2
lpips                    0.1.4
MarkupSafe               2.1.3
matplotlib               3.5.1
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.15
networkx                 3.1
nltk                     3.8.1
numpy                    1.21.0
openai                   0.27.8
opencv-python            4.7.0.72
packaging                23.1
pandas                   2.0.3
pathtools                0.1.2
Pillow                   9.5.0
pip                      23.0.1
protobuf                 3.20.0
psutil                   5.9.5
pyarrow                  13.0.0
pyparsing                3.0.9
PySocks                  1.7.1
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0.1
regex                    2023.10.3
requests                 2.26.0
safetensors              0.4.0
scikit-learn             1.2.2
scipy                    1.7.3
seaborn                  0.11.2
sentence-transformers    2.2.2
sentencepiece            0.1.99
sentry-sdk               1.32.0
setproctitle             1.3.3
setuptools               67.8.0
six                      1.16.0
smmap                    5.0.1
soupsieve                2.5
sympy                    1.12
termcolor                1.1.0
threadpoolctl            3.2.0
tokenizers               0.13.3
torch                    2.1.1+cu118
torchaudio               2.1.1+cu118
torchvision              0.16.1+cu118
tqdm                     4.65.0
transformers             4.31.0
triton                   2.1.0
typing_extensions        4.6.3
tzdata                   2023.3
urllib3                  1.26.16
wandb                    0.14.0
wcwidth                  0.2.12
wheel                    0.38.4
xformers                 0.0.22.post7
xxhash                   3.4.1
yarl                     1.9.2
zipp                     3.17.0

**Comment by lunaryan** [comment]
Hi, I re-config the accelerate and now it works!

**Comment by AAAAAAsuka** [comment]
sounds good to me!
